FROM node:22-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 default-jdk && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]